Repository FjjDessoyCaraballo/minishell, pull requests merged in 2024-07, with the labels that each got.

#3 Built-in update
  README.md
  includes/minishell.h
  src/built_ins.c
  src/built_ins2.c
  src/main.c
Labels: enhancement

#7 documentation :3
  README.md
  documentation/Tokenization.md
  outfile
Labels: documentation

#8 updating branch
  README.md
  documentation/Tokenization.md
  outfile
Labels: enhancement

#10 fixed id call and moved readme
  README.md
  includes/token.h
  src/parse/token_test.c
  src/parse/tokenizer.c
Labels: documentation, parse

#15 TOKEN
  Makefile
  includes/minishell.h
  includes/token.h
  src/parse/check_utils.c
  src/parse/chunky_check.c
  src/parse/init_token.c
  src/parse/token_test.c
  src/parse/tokenizer.c
Labels: parse

#17 single commands working, but shell exits
  includes/minishell.h
  src/execution.c
  src/init.c
  src/ll_utils2.c
  src/main.c
  src/parse/check_utils.c
  src/parse/chunky_check.c
  src/parse/ft_strtok.c
  src/parse/init_token.c
  src/parse/token_test.c
  src/parse/tokenizer.c
Labels: bug, necessary

#20 flags + token to arrays
  Makefile
  includes/minishell.h
  includes/token.h
  libft/libft.a
  minishell
  src/parse/check_utils.c
  src/parse/chunky_check.c
  src/parse/freedom.c
  src/parse/init_token.c
  src/parse/token_test.c
  src/parse/token_to_array.c
  src/parse/tokenizer.c
Labels: parse

#24 feat: executes single commands
  Makefile
  includes/minishell.h
  src/built_ins.c
  src/built_ins2.c
  src/execution.c
  src/execution_utils.c
  src/execution_utils2.c
  src/line_handler.c
  src/ll_utils2.c
  src/parse/token_to_array.c
Labels: enhancement

#25 updating main branch
  includes/minishell.h
  includes/token.h
  src/built_ins.c
  src/built_ins2.c
  src/execution.c
  src/line_handler.c
  src/main.c
  src/parse/ft_strtok.c
Labels: enhancement

#26 feat: added helper functions to find tokens; chore: restructuring execution
  Makefile
  includes/minishell.h
  libft/libft.a
  minishell
  src/init.c
  src/ll_utils2.c
  src/main.c
  src/parse/chunky_check.c
  src/parse/token_test.c
  src/parse/tokenizer.c
Labels: enhancement

#28 fix: single commands working; chore: (update) pipes under work;
  includes/minishell.h
  includes/token.h
  src/execution/built_ins2.c
  src/execution/execution.c
  src/execution/execution_utils2.c
  src/init.c
  src/ll_utils2.c
  src/parse/chunky_check.c
  src/parse/freedom.c
  src/parse/getenv.c
  src/parse/token_to_array.c
  src/parse/tokenizer.c
Labels: enhancement, necessary

#29 quotes and pipes
  Makefile
  documentation/Tokenization.md
  includes/minishell.h
  includes/token.h
  src/execution/execution.c
  src/line_handler.c
  src/parse/ft_strtok.c
  src/parse/helper.c
  src/parse/init_token.c
  src/parse/tokenizer.c
Labels: enhancement, parse

#35 fix: syntax check;
  includes/minishell.h
  src/execution/execution.c
  src/execution/execution_utils.c
  src/execution/execution_utils2.c
  src/line_handler.c
  src/main.c
  src/parse/token_to_array.c
  src/parse/tokenizer.c
Labels: enhancement, parse

#38 FIX: pipes work without hanging
  includes/minishell.h
  src/execution/execution.c
  src/execution/execution_utils.c
  src/execution/execution_utils2.c
  src/line_handler.c
  src/main.c
  src/signals.c
Labels: documentation, enhancement, necessary

#39 fix: norminetting
  includes/minishell.h
  src/execution/execution.c
  src/main.c
Labels: necessary
